services:
  date:
    image: okmaga/result-date
    build:
      dockerfile: date.dockerfile
  result:
    image: okmaga/result
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - date
